import rdflib
import pandas as pd
import numpy as np
from rdflib import Graph, RDF, URIRef, Literal
g=Graph()
g.parse('/home/melkamu/  /Documents_for_testing/English_Test_Dataset_Final', format='nt')#the english DBpedia graph
g.parse('/home/melkamu/  /Documents_for_testing/French_Test_Dataset_Final', format='nt')#the french DBpedia graph
List_obj=[]
List_sub=[]
listtrip=[]
def predicate(predicate):
        for x,y in predicate:
                List_obj.append(y)
                List_sub.append(x)
                listtrip.append((x,y))
        keys1=np.array(List_obj)
        keys2=np.array(List_sub)
        listtrip2=np.array(listtrip)
        vals1=np.unique(keys1)
        vals2=np.unique(keys2)
        vals3=np.array(len(vals1),dtype=float)/np.array(len(listtrip2),dtype=float)
        vals4=np.array(len(vals2),dtype=float)/np.array(len(listtrip2),dtype=float)
        return vals3
        #return ((np.array(len(vals1),dtype=float)/np.array(len(keys1),dtype=float))+ (np.array(len(vals2),dtype=float)/np.array(len(keys2),dtype=float)))/2                         
RDF_Type=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://www.w3.org/1999/02/22-rdf-syntax-ns#type')))
OWL_SameAs=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://www.w3.org/2002/07/owl#sameAs')))
Subject=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://purl.org/dc/terms/subject')))
Influence=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/influences')))
BirthPlace=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/birthPlace')))
Occupation=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/occupation')))
wikiPageExternalLink=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/wikiPageExternalLink')))
Country=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/country')))
profesion=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/profession')))
nationality=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/nationality')))
deathplace=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/deathPlace')))
title=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/title')))
formerteam=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/formerTeam')))
league=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/league')))
position=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/position')))
team=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/team')))
termperiod=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/termPeriod')))
website=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/website')))
careerstation=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/careerStation')))
clubs=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/clubs')))
currentclub=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/currentclub')))
nationalteam=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/nationalteam')))
youth=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/youthclubs')))
Chancellor=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/chancellor')))
party=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/party')))
religion=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/religion')))
spouse=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/spouse')))
sucees=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/successor')))
battle=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/battle')))
militaryrank=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/militaryBranch')))
relation=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/relation')))
branch=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/branch')))
rank=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/rank')))
first=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/firstRace')))
last=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/lastRace')))
strokes=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/strokes')))
collegeteam=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/collegeteam')))
associatedband=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/associatedBand')))
associatedmusic=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/associatedMusicalArtist')))
genre=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/genre')))
hometown=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/hometown')))
recordlev=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/recordLabel')))
origion=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/origin')))
word_net=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/wordnet_type')))
after=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/after')))
before=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/before')))
predecessor=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/predecessor')))
successor=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/successor')))
language=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/languagesSpoken')))
residence=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/residence')))
parent=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/parent')))
father=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/father')))
house=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/house')))
issue=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/issue')))
mother=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/mother')))
coach=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/coach')))
instrument=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/instrument')))
label=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/label')))
alongside=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/alongside')))
consitency=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/constituencyMp')))
deputy=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/deputy')))
govegene=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/governorGeneral')))
honpref=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/honorificPrefix')))
monarch=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/monarch')))
office=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/office')))
order=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/order')))
prime=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/property/primeminister')))
movie=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/movie')))
education_place=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/educationPlace')))
decoration=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/decoration')))
decipline=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/disciple')))
education=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/education')))
mentor=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/mentor')))
university=predicate(g.subject_objects(predicate=rdflib.term.URIRef(u'http://dbpedia.org/ontology/university')))
